name: Developer_Branch_CI
on:
  push:
    branches:
      - 'XPNS-*'
jobs:
  CI_Steps:
   uses: Priya-Devops2023/Priya-Organization/github-actions/.github/workflows/Developer_Branch_CI.yml@main
####KKL