name: Developer_Branch_CI
on:
  push:
    branches:
      - 'XPNS-*'
jobs:
  CI_Steps:
   path: Priya-Organization/github-actions/.github/workflows/

   uses: Priya-Organization/github-actions/.github/workflows/Developer_Branch_CI.yml@main
####KKL